[phases.setup]
aptPkgs = [
  "libxcb1",
  "libxcb-render0",
  "libxcb-shm0",
  "libxcb-icccm4",
  "libxcb-image0",
  "libxcb-keysyms1",
  "libxcb-randr0",
  "libxcb-render-util0",
  "libxcb-xinerama0",
  "libgl1",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender1"
]
